version: "3.8"

services:
  ai-companion-mysql:
    image: mysql:8.1.0
    restart: always
    ports:
      - "13306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
